name: CD
run-name: CD that deploys the Docker images to ghcr.io
on:
  workflow_run:
    workflows: ["CI Workflow that runs hadolint and shellcheck"]
    types:
      - completed

jobs:
  files_changed:
    runs-on: ubuntu-latest
    outputs:
      run_deploy: ${{ steps.files_changed.outputs.run_deploy }}
    steps:
      - uses: actions/checkout@v4
      - name: Check for relevant file changes
        id: files_changed
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qE '\.devcontainer/.*Dockerfile.*|\.devcontainer/.*\.sh$'; then
            echo "run_deploy=true" >> $GITHUB_ENV
          else
            echo "run_deploy=false" >> $GITHUB_ENV
          fi
  deploy:
    if: ${{ github.event.workflow_run.conclusion && needs.files_changed.outputs.run_deploy == 'true' }}
    needs: files_changed
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    env:
      ROS_DISTROS: "rolling jazzy iron"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR }}

      - name: Build and push
        run: |
          bash .github/build_and_push.sh
        env:
          ROS_DISTROS: ${{ env.ROS_DISTROS }}
        # Cache the osrf/${ROS_DISTRO}-desktop-full images
        # to speed up the build process
        cache:
          key: ${{ runner.os }}-ros-${{ env.ROS_DISTROS }}-desktop-full
